services:
  - type: web
    name: your-app-name-here # Buraya uygulamanızın ismini yazın
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    autoDeploy: false # GitHub Actions kullanacağımız için false yapıyoruz
